export const DUMMY_MOVIES = [
    {
      id: "1",
      title: "Jurassic Park",
      release_date: '1993',
      genre_ids: "Adventure",
      duration: "127 Min.",
      coverImage: "https://source.unsplash.com/random",
    },
    {
      id: "2",
      title: "The Godfather",
      release_date: '1972',
      genre_ids: "Crime",
      duration: "175 Min.",
      coverImage: "https://source.unsplash.com/random",
    },
    {
      id: "3",
      title: "Titanic",
      release_date: '1997',
      genre_ids: "Romance",
      duration: "195 Min.",
      coverImage: "https://source.unsplash.com/random",
    },
    {
      id: "4",
      title: "Inception",
      release_date: '2010',
      genre_ids: "Sci-Fi",
      duration: "148 Min.",
      coverImage: "https://source.unsplash.com/random",
    },
    {
      id: "5",
      title: "The Matrix",
      release_date: '1999',
      genre_ids: "Action",
      duration: "136 Min.",
      coverImage: "https://source.unsplash.com/random",
    },
  ];